# Use the official Python base image with Python 3.10
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY main.py .

# Copy the templates folder to the container
COPY Templates Templates

# Expose the port that the Flask application will be running on
EXPOSE 5001

# Set the command to run the Flask application
CMD ["python", "main.py"]
